### ISSUE TITLE
Share menu

### ISSUE THREAD

**Issue by siggi1984** [sheikhhaziq/gyawun#57]
### Feature description

Make vibemusic available in the share menu.

It would make sharing from the left easier.

**Comment by sheikhhaziq** [comment]
Can you explain which share menu

**Comment by siggi1984** [comment]
> 

VibeMusic should be offered here in this menu.

![Screenshot_20230201-080342_Android System](https://user-images.githubusercontent.com/103368536/215974370-b55fcab2-f799-4c6c-b49d-e49ebf654a1b.jpg)

**Comment by sheikhhaziq** [comment]
I have not added this feature yet... This will be added in future

**Comment by siggi1984** [comment]
The app has become unusable for me.

**Comment by sheikhhaziq** [comment]
What problems are you facing

**Comment by siggi1984** [comment]
I listen to Russian music and there is no Russian music at Jio Saavn. It's not bad. The app looks good so far.

**Comment by sheikhhaziq** [comment]
I got it, Youtube music has been remove temporarily. It will be added back next update along with Jio Saavn. Till then, you can use the previous update.

**Comment by sheikhhaziq** [comment]
You can join our telegram group for more updates

**Comment by sheikhhaziq** [comment]
[Telegram group](https://t.me/gyavun)

**Comment by DarkCrypt** [comment]
> I got it, Youtube music has been remove temporarily. It will be added back next update along with Jio Saavn. Till then, you can use the previous update.

That would be great. Jio Saavn doesn't have any music for English either.
